// Translations for Now view, planner strip, due dates, quick capture ("Add") and today's progress.
// Keys: now.*, strip.*, due.*, unit.*, progress.*, capture.*. Every key must exist in en, fr, de and es (tests/i18n.test.js).
// Use in JS: I18n.t('key', { name: value }); in HTML: data-i18n="key".
I18n.register({
  en: {
    "now.kicker.now": "NOW",
    "now.kicker.routine": "ROUTINE NOW",
    "now.kicker.event": "IN YOUR CALENDAR",
    "now.kicker.break": "BREAK",
    "now.kicker.free": "FREE TIME",
    "now.kicker.step": "{routine} · STEP {n}/{total}",
    "now.stepsBuffer": "{min} min of steps + buffer",
    "now.btn.showRoutine": "Show routine",
    "now.btn.stepDone": "Step done",
    "now.btn.startRoutine": "Start routine",
    "now.btn.editSteps": "Edit steps",
    "now.btn.skipToday": "Skip today",
    "now.btn.seeDay": "See the day",
    "now.btn.editEvent": "Edit",
    "now.event.prompt": "This event is running. Pick one:",
    "now.event.later": "In {min} min",
    "now.event.notATask": "It’s an event, not a task",
    "now.event.notATaskTitle": "Keep it in the calendar, but let tasks run during it",
    "now.event.postponed": "“{name}” moved to {time}",
    "now.event.postponeFailed": "Could not move “{name}”: the new time is taken.",
    "now.event.notATaskDone": "“{name}” stays in the calendar. Tasks can run during it.",
    "now.event.notATaskFailed": "Could not change “{name}”.",
    "now.btn.done": "Done",
    "now.btn.focus": "Focus",
    "now.btn.focusTitle": "Full-screen focus timer",
    "now.btn.notNow": "Not now",
    "now.btn.startNow": "Start it now",
    "now.btn.planDay": "Plan my day",
    "now.btn.addTask": "Add a task",
    "now.important": "important",
    "now.skip.prompt": "Not now? Pick one:",
    "now.skip.later": "Later today",
    "now.skip.tomorrow": "Tomorrow",
    "now.skip.split": "Too big: split it",
    "now.skip.cancel": "Cancel",
    "now.break.title": "Next: {name}",
    "now.break.meta": "Starts at {time}. Stretch, drink some water.",
    "now.free.title": "Nothing planned right now",
    "now.free.next": "Next: {name} at {time}.",
    "now.free.clear": "Your day is clear. Add a task or plan ahead.",
    "now.next.empty": "Nothing else today.",
    "now.timer.left": "left",
    "now.timer.stepLeft": "left in this step",
    "now.timer.over": "over time",
    "now.timer.until": "until it starts",
    "now.toast.done": "Done: {name} ✓",
    "now.doc.break": "Break · {name} in {time}",
    "unit.min": "{n} min",
    "strip.now": "Now",
    "strip.soon": "Soon",
    "strip.next": "Next",
    "strip.left": "· {time} left",
    "strip.startsIn": "· starts in {time}",
    "strip.at": "· at {time}",
    "strip.open": "Open",
    "due.on": "due {when}",
    "due.overdue": "overdue since {date}",
    "due.today": "today",
    "due.tomorrow": "tomorrow",
    "capture.placeholder": "e.g. “Call mom tomorrow at 5pm for 20 min !7”",
    "capture.hint": "Say when (“at 5pm”, “tomorrow”), how long (“for 20 min”) and how important (“!7”). No time = the app fits it into a free slot.",
    "capture.adding": "Adding…",
    "capture.listening": "Listening…",
    "capture.notUnderstood": "Could not understand that — try \"Call mom tomorrow at 5pm\".",
    "capture.added": "Added “{name}” — {details}.",
    "capture.scheduled": "scheduled {date}",
    "capture.due": "due {date}",
    "capture.importance": "importance {n}",
    "capture.fixed": "fixed",
    "capture.byAI": "understood by AI",
    "capture.offline": "parsed offline",
    "capture.moved": "{time} was taken by “{name}”, so it is at {newTime}.",
    "capture.dayFull": "That day is full, so it waits in your task list.",
    "capture.breakdown": "Break it down",
    "progress.heading": "Today’s progress",
    "progress.tasksDone": "tasks done",
    "progress.points": "points earned",
    "progress.minutes": "focused minutes",
    "progress.coach": "AI encouragement",
    "progress.thinking": "Thinking…",
  },
  fr: {
    "now.kicker.now": "MAINTENANT",
    "now.kicker.routine": "ROUTINE EN COURS",
    "now.kicker.event": "DANS VOTRE AGENDA",
    "now.kicker.break": "PAUSE",
    "now.kicker.free": "TEMPS LIBRE",
    "now.kicker.step": "{routine} · ÉTAPE {n}/{total}",
    "now.stepsBuffer": "{min} min d’étapes + marge",
    "now.btn.showRoutine": "Afficher la routine",
    "now.btn.stepDone": "Étape faite",
    "now.btn.startRoutine": "Démarrer la routine",
    "now.btn.editSteps": "Modifier les étapes",
    "now.btn.skipToday": "Sauter aujourd’hui",
    "now.btn.seeDay": "Voir la journée",
    "now.btn.editEvent": "Modifier",
    "now.event.prompt": "Cet événement est en cours. Choisissez :",
    "now.event.later": "Dans {min} min",
    "now.event.notATask": "C’est un événement, pas une tâche",
    "now.event.notATaskTitle": "Le garder dans l’agenda, mais laisser les tâches passer pendant",
    "now.event.postponed": "« {name} » décalé à {time}",
    "now.event.postponeFailed": "Impossible de décaler « {name} » : le nouveau créneau est pris.",
    "now.event.notATaskDone": "« {name} » reste dans l’agenda. Les tâches peuvent s’y glisser.",
    "now.event.notATaskFailed": "Impossible de modifier « {name} ».",
    "now.btn.done": "Fait",
    "now.btn.focus": "Focus",
    "now.btn.focusTitle": "Minuteur de concentration plein écran",
    "now.btn.notNow": "Pas maintenant",
    "now.btn.startNow": "Commencer maintenant",
    "now.btn.planDay": "Planifier ma journée",
    "now.btn.addTask": "Ajouter une tâche",
    "now.important": "important",
    "now.skip.prompt": "Pas maintenant ? Choisissez :",
    "now.skip.later": "Plus tard aujourd’hui",
    "now.skip.tomorrow": "Demain",
    "now.skip.split": "Trop gros : découper",
    "now.skip.cancel": "Annuler",
    "now.break.title": "Ensuite : {name}",
    "now.break.meta": "Commence à {time}. Étirez-vous, buvez un peu d’eau.",
    "now.free.title": "Rien de prévu pour l’instant",
    "now.free.next": "Ensuite : {name} à {time}.",
    "now.free.clear": "Votre journée est libre. Ajoutez une tâche ou planifiez.",
    "now.next.empty": "Plus rien aujourd’hui.",
    "now.timer.left": "restant",
    "now.timer.stepLeft": "restant pour cette étape",
    "now.timer.over": "de dépassement",
    "now.timer.until": "avant le début",
    "now.toast.done": "Fait : {name} ✓",
    "now.doc.break": "Pause · {name} dans {time}",
    "unit.min": "{n} min",
    "strip.now": "Maintenant",
    "strip.soon": "Bientôt",
    "strip.next": "Ensuite",
    "strip.left": "· encore {time}",
    "strip.startsIn": "· commence dans {time}",
    "strip.at": "· à {time}",
    "strip.open": "Ouvrir",
    "due.on": "échéance {when}",
    "due.overdue": "en retard depuis le {date}",
    "due.today": "aujourd’hui",
    "due.tomorrow": "demain",
    "capture.placeholder": "ex. « Call mom tomorrow at 5pm for 20 min !7 »",
    "capture.hint": "Dites quand (« at 5pm », « tomorrow »), combien de temps (« for 20 min ») et l’importance (« !7 »). Sans heure, l’application la place dans un créneau libre. Sans IA, écrivez en anglais.",
    "capture.adding": "Ajout…",
    "capture.listening": "J’écoute…",
    "capture.notUnderstood": "Je n’ai pas compris — essayez « Call mom tomorrow at 5pm ».",
    "capture.added": "« {name} » ajoutée — {details}.",
    "capture.scheduled": "prévue le {date}",
    "capture.due": "échéance {date}",
    "capture.importance": "importance {n}",
    "capture.fixed": "heure fixe",
    "capture.byAI": "comprise par l’IA",
    "capture.offline": "analysée hors ligne",
    "capture.moved": "{time} était pris par « {name} », elle est donc à {newTime}.",
    "capture.dayFull": "Cette journée est pleine, la tâche attend dans votre liste.",
    "capture.breakdown": "La découper",
    "progress.heading": "Progrès du jour",
    "progress.tasksDone": "tâches faites",
    "progress.points": "points gagnés",
    "progress.minutes": "minutes de concentration",
    "progress.coach": "Encouragement de l’IA",
    "progress.thinking": "Réflexion…",
  },
  de: {
    "now.kicker.now": "JETZT",
    "now.kicker.routine": "ROUTINE JETZT",
    "now.kicker.event": "IN DEINEM KALENDER",
    "now.kicker.break": "PAUSE",
    "now.kicker.free": "FREIE ZEIT",
    "now.kicker.step": "{routine} · SCHRITT {n}/{total}",
    "now.stepsBuffer": "{min} Min Schritte + Puffer",
    "now.btn.showRoutine": "Routine anzeigen",
    "now.btn.stepDone": "Schritt erledigt",
    "now.btn.startRoutine": "Routine starten",
    "now.btn.editSteps": "Schritte bearbeiten",
    "now.btn.skipToday": "Heute auslassen",
    "now.btn.seeDay": "Tag ansehen",
    "now.btn.editEvent": "Ändern",
    "now.event.prompt": "Dieser Termin läuft gerade. Wähle:",
    "now.event.later": "In {min} Min",
    "now.event.notATask": "Ist ein Termin, keine Aufgabe",
    "now.event.notATaskTitle": "Im Kalender behalten, aber Aufgaben währenddessen erlauben",
    "now.event.postponed": "„{name}“ auf {time} verschoben",
    "now.event.postponeFailed": "„{name}“ konnte nicht verschoben werden: Die neue Zeit ist belegt.",
    "now.event.notATaskDone": "„{name}“ bleibt im Kalender. Aufgaben können währenddessen laufen.",
    "now.event.notATaskFailed": "„{name}“ konnte nicht geändert werden.",
    "now.btn.done": "Erledigt",
    "now.btn.focus": "Fokus",
    "now.btn.focusTitle": "Fokus-Timer im Vollbild",
    "now.btn.notNow": "Nicht jetzt",
    "now.btn.startNow": "Jetzt starten",
    "now.btn.planDay": "Tag planen",
    "now.btn.addTask": "Aufgabe hinzufügen",
    "now.important": "wichtig",
    "now.skip.prompt": "Nicht jetzt? Wähle:",
    "now.skip.later": "Später heute",
    "now.skip.tomorrow": "Morgen",
    "now.skip.split": "Zu groß: aufteilen",
    "now.skip.cancel": "Abbrechen",
    "now.break.title": "Als Nächstes: {name}",
    "now.break.meta": "Beginnt um {time}. Streck dich, trink etwas Wasser.",
    "now.free.title": "Gerade nichts geplant",
    "now.free.next": "Als Nächstes: {name} um {time}.",
    "now.free.clear": "Dein Tag ist frei. Füge eine Aufgabe hinzu oder plane voraus.",
    "now.next.empty": "Heute nichts mehr.",
    "now.timer.left": "übrig",
    "now.timer.stepLeft": "übrig für diesen Schritt",
    "now.timer.over": "überzogen",
    "now.timer.until": "bis zum Beginn",
    "now.toast.done": "Erledigt: {name} ✓",
    "now.doc.break": "Pause · {name} in {time}",
    "unit.min": "{n} Min",
    "strip.now": "Jetzt",
    "strip.soon": "Gleich",
    "strip.next": "Als Nächstes",
    "strip.left": "· noch {time}",
    "strip.startsIn": "· beginnt in {time}",
    "strip.at": "· um {time}",
    "strip.open": "Öffnen",
    "due.on": "fällig {when}",
    "due.overdue": "überfällig seit {date}",
    "due.today": "heute",
    "due.tomorrow": "morgen",
    "capture.placeholder": "z. B. „Call mom tomorrow at 5pm for 20 min !7“",
    "capture.hint": "Sag wann („at 5pm“, „tomorrow“), wie lange („for 20 min“) und wie wichtig („!7“). Ohne Uhrzeit sucht die App eine freie Lücke. Ohne KI bitte auf Englisch schreiben.",
    "capture.adding": "Wird hinzugefügt…",
    "capture.listening": "Ich höre zu…",
    "capture.notUnderstood": "Nicht verstanden — versuche „Call mom tomorrow at 5pm“.",
    "capture.added": "„{name}“ hinzugefügt — {details}.",
    "capture.scheduled": "geplant {date}",
    "capture.due": "fällig {date}",
    "capture.importance": "Wichtigkeit {n}",
    "capture.fixed": "feste Zeit",
    "capture.byAI": "von der KI verstanden",
    "capture.offline": "offline erkannt",
    "capture.moved": "{time} war durch „{name}“ belegt, daher um {newTime}.",
    "capture.dayFull": "Dieser Tag ist voll, die Aufgabe wartet in deiner Liste.",
    "capture.breakdown": "Aufteilen",
    "progress.heading": "Fortschritt heute",
    "progress.tasksDone": "Aufgaben erledigt",
    "progress.points": "Punkte verdient",
    "progress.minutes": "Minuten Fokus",
    "progress.coach": "Ermutigung von der KI",
    "progress.thinking": "Denke nach…",
  },
  es: {
    "now.kicker.now": "AHORA",
    "now.kicker.routine": "RUTINA AHORA",
    "now.kicker.event": "EN TU CALENDARIO",
    "now.kicker.break": "PAUSA",
    "now.kicker.free": "TIEMPO LIBRE",
    "now.kicker.step": "{routine} · PASO {n}/{total}",
    "now.stepsBuffer": "{min} min de pasos + margen",
    "now.btn.showRoutine": "Ver la rutina",
    "now.btn.stepDone": "Paso hecho",
    "now.btn.startRoutine": "Empezar la rutina",
    "now.btn.editSteps": "Editar pasos",
    "now.btn.skipToday": "Saltar hoy",
    "now.btn.seeDay": "Ver el día",
    "now.btn.editEvent": "Editar",
    "now.event.prompt": "Este evento está en curso. Elige:",
    "now.event.later": "En {min} min",
    "now.event.notATask": "Es un evento, no una tarea",
    "now.event.notATaskTitle": "Dejarlo en el calendario, pero dejar pasar tareas durante él",
    "now.event.postponed": "«{name}» movido a las {time}",
    "now.event.postponeFailed": "No se pudo mover «{name}»: la nueva hora está ocupada.",
    "now.event.notATaskDone": "«{name}» se queda en el calendario. Las tareas pueden hacerse durante él.",
    "now.event.notATaskFailed": "No se pudo cambiar «{name}».",
    "now.btn.done": "Hecho",
    "now.btn.focus": "Enfoque",
    "now.btn.focusTitle": "Temporizador de enfoque a pantalla completa",
    "now.btn.notNow": "Ahora no",
    "now.btn.startNow": "Empezar ahora",
    "now.btn.planDay": "Planificar mi día",
    "now.btn.addTask": "Añadir una tarea",
    "now.important": "importante",
    "now.skip.prompt": "¿Ahora no? Elige:",
    "now.skip.later": "Más tarde hoy",
    "now.skip.tomorrow": "Mañana",
    "now.skip.split": "Demasiado grande: dividir",
    "now.skip.cancel": "Cancelar",
    "now.break.title": "Después: {name}",
    "now.break.meta": "Empieza a las {time}. Estírate, bebe un poco de agua.",
    "now.free.title": "Nada previsto ahora",
    "now.free.next": "Después: {name} a las {time}.",
    "now.free.clear": "Tu día está libre. Añade una tarea o planifica.",
    "now.next.empty": "Nada más hoy.",
    "now.timer.left": "restante",
    "now.timer.stepLeft": "restante en este paso",
    "now.timer.over": "de más",
    "now.timer.until": "para empezar",
    "now.toast.done": "Hecho: {name} ✓",
    "now.doc.break": "Pausa · {name} en {time}",
    "unit.min": "{n} min",
    "strip.now": "Ahora",
    "strip.soon": "Pronto",
    "strip.next": "Después",
    "strip.left": "· quedan {time}",
    "strip.startsIn": "· empieza en {time}",
    "strip.at": "· a las {time}",
    "strip.open": "Abrir",
    "due.on": "vence {when}",
    "due.overdue": "atrasada desde el {date}",
    "due.today": "hoy",
    "due.tomorrow": "mañana",
    "capture.placeholder": "p. ej. «Call mom tomorrow at 5pm for 20 min !7»",
    "capture.hint": "Di cuándo («at 5pm», «tomorrow»), cuánto dura («for 20 min») y su importancia («!7»). Sin hora, la aplicación busca un hueco libre. Sin IA, escribe en inglés.",
    "capture.adding": "Añadiendo…",
    "capture.listening": "Escuchando…",
    "capture.notUnderstood": "No lo entendí — prueba «Call mom tomorrow at 5pm».",
    "capture.added": "«{name}» añadida — {details}.",
    "capture.scheduled": "prevista el {date}",
    "capture.due": "vence {date}",
    "capture.importance": "importancia {n}",
    "capture.fixed": "hora fija",
    "capture.byAI": "entendida por la IA",
    "capture.offline": "analizada sin conexión",
    "capture.moved": "{time} estaba ocupado por «{name}», así que queda a las {newTime}.",
    "capture.dayFull": "Ese día está lleno, la tarea espera en tu lista.",
    "capture.breakdown": "Dividirla",
    "progress.heading": "Progreso de hoy",
    "progress.tasksDone": "tareas hechas",
    "progress.points": "puntos ganados",
    "progress.minutes": "minutos de enfoque",
    "progress.coach": "Ánimo de la IA",
    "progress.thinking": "Pensando…",
  },
});
