// Translations for Routine editor and full-screen routine player.
// Keys: routine.*, player.*. Every key must exist in en, fr, de and es (tests/i18n.test.js).
// Use in JS: I18n.t('key', { name: value }); in HTML: data-i18n="key".
I18n.register({
  en: {
    "routine.overlap": "“{name}” ({start}, {min} min with buffer) overlaps “{other}” at {otherStart}. Pick another time or other days.",
    "routine.bookingNote": "A routine books its time in your day plan (steps + buffer from Settings). Nothing else can be scheduled on top of it.",
    "routine.meta": "{n} steps · {min} min (books {booked})",
    "routine.empty": "No routines yet. Tap \"New\", or start from an example:",
    "routine.stepName": "Step name",
    "routine.duration": "Duration (min)",
    "routine.moveUp": "Move up",
    "routine.moveDown": "Move down",
    "routine.drag": "Drag to change the order",
    "routine.removeStep": "Remove this step",
    "routine.editStep": "Show duration and options",
    "routine.reorderHint": "Tap a step to change its duration. Drag ⋮⋮ or use the arrows to change the order.",
    "player.stepOf": "Step {n} of {total}",
    "player.finishBy": "Finish by {time}",
    "player.complete": "Step done",
    "player.skip": "Skip",
    "player.upcoming": "Coming next",
    "player.remaining": "remaining",
    "player.autoRun": "Auto run",
    "player.exit": "Exit",
  },
  fr: {
    "routine.overlap": "« {name} » ({start}, {min} min avec la marge) chevauche « {other} » à {otherStart}. Choisissez une autre heure ou d’autres jours.",
    "routine.bookingNote": "Une routine réserve son temps dans votre planning (étapes + marge définie dans les paramètres). Rien d’autre ne peut être prévu en même temps.",
    "routine.meta": "{n} étapes · {min} min (réserve {booked})",
    "routine.empty": "Aucune routine. Touchez « Nouvelle » ou partez d’un exemple :",
    "routine.stepName": "Nom de l’étape",
    "routine.duration": "Durée (min)",
    "routine.moveUp": "Monter",
    "routine.moveDown": "Descendre",
    "routine.drag": "Glisser pour changer l’ordre",
    "routine.removeStep": "Supprimer cette étape",
    "routine.editStep": "Afficher la durée et les options",
    "routine.reorderHint": "Touchez une étape pour changer sa durée. Glissez ⋮⋮ ou utilisez les flèches pour changer l’ordre.",
    "player.stepOf": "Étape {n} sur {total}",
    "player.finishBy": "Fin vers {time}",
    "player.complete": "Étape faite",
    "player.skip": "Passer",
    "player.upcoming": "Ensuite",
    "player.remaining": "restant",
    "player.autoRun": "Enchaîner seul",
    "player.exit": "Quitter",
  },
  de: {
    "routine.overlap": "„{name}“ ({start}, {min} Min mit Puffer) überschneidet sich mit „{other}“ um {otherStart}. Wähle eine andere Zeit oder andere Tage.",
    "routine.bookingNote": "Eine Routine reserviert ihre Zeit im Tagesplan (Schritte + Puffer aus den Einstellungen). Zur selben Zeit kann nichts anderes geplant werden.",
    "routine.meta": "{n} Schritte · {min} Min (reserviert {booked})",
    "routine.empty": "Noch keine Routinen. Tippe auf „Neu“ oder starte mit einem Beispiel:",
    "routine.stepName": "Name des Schritts",
    "routine.duration": "Dauer (Min)",
    "routine.moveUp": "Nach oben",
    "routine.moveDown": "Nach unten",
    "routine.drag": "Ziehen, um die Reihenfolge zu ändern",
    "routine.removeStep": "Diesen Schritt löschen",
    "routine.editStep": "Dauer und Optionen zeigen",
    "routine.reorderHint": "Tippe auf einen Schritt, um seine Dauer zu ändern. Ziehe ⋮⋮ oder nutze die Pfeile, um die Reihenfolge zu ändern.",
    "player.stepOf": "Schritt {n} von {total}",
    "player.finishBy": "Fertig um {time}",
    "player.complete": "Schritt erledigt",
    "player.skip": "Überspringen",
    "player.upcoming": "Als Nächstes",
    "player.remaining": "übrig",
    "player.autoRun": "Automatisch weiter",
    "player.exit": "Beenden",
  },
  es: {
    "routine.overlap": "«{name}» ({start}, {min} min con margen) se solapa con «{other}» a las {otherStart}. Elige otra hora u otros días.",
    "routine.bookingNote": "Una rutina reserva su tiempo en tu plan del día (pasos + margen de los Ajustes). No se puede programar nada más a la vez.",
    "routine.meta": "{n} pasos · {min} min (reserva {booked})",
    "routine.empty": "Aún no hay rutinas. Toca «Nueva» o empieza con un ejemplo:",
    "routine.stepName": "Nombre del paso",
    "routine.duration": "Duración (min)",
    "routine.moveUp": "Subir",
    "routine.moveDown": "Bajar",
    "routine.drag": "Arrastra para cambiar el orden",
    "routine.removeStep": "Borrar este paso",
    "routine.editStep": "Mostrar duración y opciones",
    "routine.reorderHint": "Toca un paso para cambiar su duración. Arrastra ⋮⋮ o usa las flechas para cambiar el orden.",
    "player.stepOf": "Paso {n} de {total}",
    "player.finishBy": "Termina hacia las {time}",
    "player.complete": "Paso hecho",
    "player.skip": "Saltar",
    "player.upcoming": "Después",
    "player.remaining": "restante",
    "player.autoRun": "Seguir solo",
    "player.exit": "Salir",
  },
});
