// Translations for Day planner: "Plan ahead" panel, legend, time conflicts, add/edit event form.
// Keys: plan.*, legend.*, conflict.*, event.*. Every key must exist in en, fr, de and es (tests/i18n.test.js).
// Use in JS: I18n.t('key', { name: value }); in HTML: data-i18n="key".
I18n.register({
  en: {
    "plan.ahead": "Plan ahead",
    "plan.hint": "Deadlines and big tasks. Split big ones into small steps (15–30 min) so they fit in your day.",
    "plan.empty": "No deadlines coming. Add one with “by Friday” in Add.",
    "plan.planned": "planned {date}",
    "plan.split": "Split",
    "plan.splitTitle": "Break it into small steps",
    "plan.delete": "Delete this task",
    "plan.deleteOverdue": "Delete all overdue ({n})",
    "plan.deleted": "{n} task(s) deleted.",
    "plan.undo": "Undo",
    "plan.more": "+ {n} more",
    "legend.routine": "Routine (booked + buffer)",
    "legend.fixed": "Fixed",
    "legend.flexible": "Auto-placed",
    "legend.calendar": "Calendar",
    "conflict.taken": "This time is already taken by {names}.",
    "conflict.nextFree": "The next free slot is {time}.",
    "event.titleAdd": "New event",
    "event.titleEdit": "Edit",
    "event.titleSchedule": "Plan this task",
    "event.what": "What?",
    "event.whatPlaceholder": "e.g. Call the dentist",
    "event.when": "Start",
    "event.howLong": "How long? (minutes)",
    "event.more": "More options",
    "event.fromList": "Or pick a task from your list",
    "event.importance": "Importance (1–10)",
    "event.urgency": "Urgency (1–10)",
    "event.deadline": "Deadline",
    "event.dependency": "Do this after",
    "event.remove": "Delete",
    "event.cancel": "Cancel",
    "event.save": "Save",
    "event.useFree": "Use {time}",
  },
  fr: {
    "plan.ahead": "À planifier",
    "plan.hint": "Échéances et grosses tâches. Découpez les grosses en petites étapes (15–30 min) pour qu’elles tiennent dans votre journée.",
    "plan.empty": "Aucune échéance à venir. Ajoutez-en une avec « by Friday » dans Ajouter.",
    "plan.planned": "prévu le {date}",
    "plan.split": "Découper",
    "plan.splitTitle": "La découper en petites étapes",
    "plan.delete": "Supprimer cette tâche",
    "plan.deleteOverdue": "Supprimer tout le retard ({n})",
    "plan.deleted": "{n} tâche(s) supprimée(s).",
    "plan.undo": "Annuler",
    "plan.more": "+ {n} autres",
    "legend.routine": "Routine (réservée + marge)",
    "legend.fixed": "Heure fixe",
    "legend.flexible": "Placée automatiquement",
    "legend.calendar": "Agenda",
    "conflict.taken": "Ce créneau est déjà pris par {names}.",
    "conflict.nextFree": "Le prochain créneau libre est à {time}.",
    "event.titleAdd": "Nouvel événement",
    "event.titleEdit": "Modifier",
    "event.titleSchedule": "Planifier cette tâche",
    "event.what": "Quoi ?",
    "event.whatPlaceholder": "ex. Appeler le dentiste",
    "event.when": "Début",
    "event.howLong": "Combien de temps ? (minutes)",
    "event.more": "Plus d’options",
    "event.fromList": "Ou choisir une tâche de votre liste",
    "event.importance": "Importance (1–10)",
    "event.urgency": "Urgence (1–10)",
    "event.deadline": "Échéance",
    "event.dependency": "À faire après",
    "event.remove": "Supprimer",
    "event.cancel": "Annuler",
    "event.save": "Enregistrer",
    "event.useFree": "Prendre {time}",
  },
  de: {
    "plan.ahead": "Vorausplanen",
    "plan.hint": "Fristen und große Aufgaben. Teile große Aufgaben in kleine Schritte (15–30 Min), damit sie in deinen Tag passen.",
    "plan.empty": "Keine Fristen in Sicht. Füge eine mit „by Friday“ unter Neu hinzu.",
    "plan.planned": "geplant {date}",
    "plan.split": "Aufteilen",
    "plan.splitTitle": "In kleine Schritte aufteilen",
    "plan.delete": "Diese Aufgabe löschen",
    "plan.deleteOverdue": "Alle überfälligen löschen ({n})",
    "plan.deleted": "{n} Aufgabe(n) gelöscht.",
    "plan.undo": "Rückgängig",
    "plan.more": "+ {n} weitere",
    "legend.routine": "Routine (reserviert + Puffer)",
    "legend.fixed": "Feste Zeit",
    "legend.flexible": "Automatisch platziert",
    "legend.calendar": "Kalender",
    "conflict.taken": "Diese Zeit ist schon belegt durch {names}.",
    "conflict.nextFree": "Die nächste freie Zeit ist {time}.",
    "event.titleAdd": "Neuer Termin",
    "event.titleEdit": "Bearbeiten",
    "event.titleSchedule": "Diese Aufgabe planen",
    "event.what": "Was?",
    "event.whatPlaceholder": "z. B. Zahnarzt anrufen",
    "event.when": "Beginn",
    "event.howLong": "Wie lange? (Minuten)",
    "event.more": "Weitere Optionen",
    "event.fromList": "Oder eine Aufgabe aus deiner Liste wählen",
    "event.importance": "Wichtigkeit (1–10)",
    "event.urgency": "Dringlichkeit (1–10)",
    "event.deadline": "Frist",
    "event.dependency": "Erst nach",
    "event.remove": "Löschen",
    "event.cancel": "Abbrechen",
    "event.save": "Speichern",
    "event.useFree": "{time} nehmen",
  },
  es: {
    "plan.ahead": "Planificar",
    "plan.hint": "Fechas límite y tareas grandes. Divide las grandes en pasos pequeños (15–30 min) para que quepan en tu día.",
    "plan.empty": "No hay fechas límite próximas. Añade una con «by Friday» en Añadir.",
    "plan.planned": "prevista el {date}",
    "plan.split": "Dividir",
    "plan.splitTitle": "Dividirla en pasos pequeños",
    "plan.delete": "Borrar esta tarea",
    "plan.deleteOverdue": "Borrar todas las atrasadas ({n})",
    "plan.deleted": "{n} tarea(s) borrada(s).",
    "plan.undo": "Deshacer",
    "plan.more": "+ {n} más",
    "legend.routine": "Rutina (reservada + margen)",
    "legend.fixed": "Hora fija",
    "legend.flexible": "Colocada automáticamente",
    "legend.calendar": "Calendario",
    "conflict.taken": "Esta hora ya está ocupada por {names}.",
    "conflict.nextFree": "El siguiente hueco libre es a las {time}.",
    "event.titleAdd": "Nuevo evento",
    "event.titleEdit": "Editar",
    "event.titleSchedule": "Planificar esta tarea",
    "event.what": "¿Qué?",
    "event.whatPlaceholder": "p. ej. Llamar al dentista",
    "event.when": "Inicio",
    "event.howLong": "¿Cuánto dura? (minutos)",
    "event.more": "Más opciones",
    "event.fromList": "O elige una tarea de tu lista",
    "event.importance": "Importancia (1–10)",
    "event.urgency": "Urgencia (1–10)",
    "event.deadline": "Fecha límite",
    "event.dependency": "Hacer después de",
    "event.remove": "Borrar",
    "event.cancel": "Cancelar",
    "event.save": "Guardar",
    "event.useFree": "Usar {time}",
  },
});
